security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        hwi_provider:
             id: thumbtackApp.oauth_user_provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                always_use_default_target_path: true
                default_target_path: /
            #http_basic:

            oauth:
                            resource_owners:
                                google:        "/login/check-google"
                                facebook:        "/login/check-facebook"
                                bitbucket:        "/login/check-bitbucket"
                            login_path:        /signIn
                            failure_path:      /signIn
                            oauth_user_provider:
                                service:  thumbtackApp.oauth_user_provider
                            default_target_path: /
            logout:
                path:   /logout
                target: /
                invalidate_session: false
    access_control:
        - { path: ^/signin, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/uploads, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/preview, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY  }
        - { path: ^/$, roles: IS_AUTHENTICATED_FULLY  }
        - { path: ^/stat$, roles: IS_AUTHENTICATED_FULLY  }
        - { path: ^/tasks, roles: IS_AUTHENTICATED_FULLY  }
        - { path: ^/domains, roles: IS_AUTHENTICATED_FULLY  }
        - { path: ^/search$, roles: IS_AUTHENTICATED_FULLY  }
