parameters:
#    thumbtackOffliner.example.class: Thumbtack\OfflinerBundle\Example
services:
#    thumbtackOffliner.example:
#        class: %thumbtackOffliner.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
 thumbtackOffliner.menu_builder:
        class: Thumbtack\OfflinerBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

 thumbtackOffliner.menu.main:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: thumbtackOffliner.menu_builder
        factory_method: mainMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu
 thumbtackoffliner.oauth_user_provider:
        class: Thumbtack\OfflinerBundle\Security\UserProvider
        arguments: [@doctrine]
